// Code generated by cmd/gencontract. DO NOT EDIT.
//
// The bounds and vocabularies the ticket endpoints validate against, taken from
// the ticket module. A form cannot render a category select, and a filter cannot
// render a status one, without knowing the values — so this file is not a
// second copy of the validation rules. It is the vocabulary those rules use,
// generated rather than transcribed.
//
// The server remains the only authority. Anything this file lets through is
// still checked there, and the field errors it returns are what the UI
// displays. STATUSES is a filter and a set of labels; a client never chooses
// what state a ticket is in.
//
// Regenerate with `make contract`. A Go test fails while this file is stale.

export const MAX_TITLE_LENGTH = 200;
export const MAX_DESCRIPTION_LENGTH = 10000;

export const CATEGORIES = [
  "billing",
  "technical",
  "account",
  "other",
] as const;
export type Category = (typeof CATEGORIES)[number];

export const PRIORITIES = [
  "urgent",
  "high",
  "normal",
  "low",
] as const;
export type Priority = (typeof PRIORITIES)[number];

export const STATUSES = [
  "open",
  "pending",
  "resolved",
  "closed",
] as const;
export type TicketStatus = (typeof STATUSES)[number];
