package http

import (
	"fmt"
	"strings"

	"github.com/JoseDavidGarciaDowning/sla-desk/internal/modules/ticket/domain"
)

// Contract is the part of POST /api/tickets a client has to know before it can
// build a request: how long the text fields may be, and which categories and
// priorities exist.
//
// This is not the validation logic. The rules stay in Validate, on the server,
// where they are the only ones that decide anything. What travels to the
// frontend is the vocabulary — and it has to travel, because a form cannot
// render a category select without knowing the categories. The choice is not
// between duplicating and not duplicating; it is between generating the copy
// and transcribing it by hand.
type Contract struct {
	MaxTitleLength       int
	MaxDescriptionLength int
	Categories           []domain.Category
	Priorities           []domain.Priority

	// Statuses are never accepted in a create body — the client does not choose
	// what state a ticket is in. They travel anyway because the list endpoint
	// takes one as a filter, and because the UI has to label them.
	Statuses []domain.Status

	// Roles are the actor roles the state machine keys its edges on. They are
	// the ticket module's own vocabulary, not the identity module's: this one
	// says what somebody was when they acted (docs/adr/0005).
	Roles []domain.Role

	// Transitions is the state machine as data — from which status, to which,
	// and by whom.
	//
	// It travels for the same reason the categories do: an agent's ticket view
	// has to offer the moves that are possible from where the ticket is, and it
	// cannot know them without being told. Transcribing the table in TypeScript
	// is the alternative, and it is the one that breaks silently — the day an
	// edge changes in docs/spec.md §4.1, the button stays on screen and the API
	// starts refusing it.
	//
	// The server remains the only authority. Anything this table lets a client
	// offer is still checked by domain.Transition, which answers 403 for an
	// edge a role may not take and a field error for one that does not exist.
	Transitions map[domain.Status]map[domain.Status][]domain.Role
}

// TicketContract describes what POST /api/tickets accepts.
//
// The slices are the same ones Validate checks against, not copies of them, so
// a category added to the API is in the contract by construction. The bounds
// are the same constants. The test that matters proves this by measurement
// anyway: it calls Validate at each boundary rather than comparing constants to
// themselves.
func TicketContract() Contract {
	return Contract{
		MaxTitleLength:       maxTitleLength,
		MaxDescriptionLength: maxDescriptionLength,
		Categories:           validCategories,
		Priorities:           validPriorities,
		Statuses:             validStatuses,
		Roles:                domain.ActorRoles(),
		Transitions:          domain.Edges(),
	}
}

// tsHeader explains the file to whoever opens it in the frontend, where there
// is no other clue that a Go program wrote it.
const tsHeader = `// Code generated by cmd/gencontract. DO NOT EDIT.
//
// The bounds and vocabularies the ticket endpoints validate against, taken from
// internal/api. A form cannot render a category select, and a filter cannot
// render a status one, without knowing the values — so this file is not a
// second copy of the validation rules. It is the vocabulary those rules use,
// generated rather than transcribed.
//
// The server remains the only authority. Anything this file lets through is
// still checked there, and the field errors it returns are what the UI
// displays. STATUSES is a filter and a set of labels; a client never chooses
// what state a ticket is in.
//
// Regenerate with ` + "`make contract`" + `. A Go test fails while this file is stale.
`

// TypeScript renders the contract as a module for the frontend.
//
// The vocabularies come out as ` + "`as const`" + ` arrays so TypeScript infers a union
// of the literals rather than string[]: a component that switches on a category
// then fails to compile when one is added, which is the point of generating
// this at all.
func (c Contract) TypeScript() string {
	var b strings.Builder

	b.WriteString(tsHeader)
	fmt.Fprintf(&b, "\nexport const MAX_TITLE_LENGTH = %d;\n", c.MaxTitleLength)
	fmt.Fprintf(&b, "export const MAX_DESCRIPTION_LENGTH = %d;\n", c.MaxDescriptionLength)

	writeTSUnion(&b, "CATEGORIES", "Category", c.Categories)
	writeTSUnion(&b, "PRIORITIES", "Priority", c.Priorities)
	writeTSUnion(&b, "STATUSES", "TicketStatus", c.Statuses)
	writeTSUnion(&b, "ACTOR_ROLES", "ActorRole", c.Roles)
	writeTSTransitions(&b, c)

	return b.String()
}

// writeTSTransitions emits the state machine as a frozen lookup.
//
// Keyed by every status including the ones with no outgoing edges, so a caller
// can index it without a guard — closed is the only such status today, and its
// empty object is what says "terminal" rather than "forgotten".
//
// The statuses are emitted in the order the domain lists them rather than in
// map order, because Go randomises the latter and a generated file that changes
// on every run would be a diff nobody can read and a staleness test that never
// passes twice.
func writeTSTransitions(b *strings.Builder, c Contract) {
	b.WriteString("\nexport const TRANSITIONS: Record<\n")
	b.WriteString("  TicketStatus,\n")
	b.WriteString("  Partial<Record<TicketStatus, readonly ActorRole[]>>\n")
	b.WriteString("> = {\n")

	for _, from := range c.Statuses {
		targets := c.Transitions[from]
		if len(targets) == 0 {
			fmt.Fprintf(b, "  %q: {},\n", string(from))
			continue
		}

		fmt.Fprintf(b, "  %q: {\n", string(from))
		// Iterate the status list again rather than the inner map, for the
		// same reason: a stable order.
		for _, to := range c.Statuses {
			roles, ok := targets[to]
			if !ok {
				continue
			}
			fmt.Fprintf(b, "    %q: [", string(to))
			for i, role := range roles {
				if i > 0 {
					b.WriteString(", ")
				}
				fmt.Fprintf(b, "%q", string(role))
			}
			b.WriteString("],\n")
		}
		b.WriteString("  },\n")
	}

	b.WriteString("} as const;\n")
}

// writeTSUnion emits a frozen array and the union type derived from it.
//
// One value per line rather than one long line: the file is read in diffs, and
// adding a category should show as one added line rather than as a rewritten
// one.
func writeTSUnion[T ~string](b *strings.Builder, constName, typeName string, values []T) {
	fmt.Fprintf(b, "\nexport const %s = [\n", constName)
	for _, v := range values {
		fmt.Fprintf(b, "  %q,\n", string(v))
	}
	fmt.Fprintf(b, "] as const;\nexport type %s = (typeof %s)[number];\n", typeName, constName)
}
