// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sladb

import (
	"time"

	domain "github.com/JoseDavidGarciaDowning/sla-desk/internal/modules/sla/domain"
)

type SlaPolicy struct {
	ID            int64
	Name          string
	Priority      domain.Priority
	BudgetMinutes int32
	ScheduleMode  string
	Active        bool
	CreatedAt     time.Time
}
