// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sla_policies.sql

package sladb

import (
	"context"

	domain "github.com/JoseDavidGarciaDowning/sla-desk/internal/modules/sla/domain"
)

const getActiveSLAPolicyByPriority = `-- name: GetActiveSLAPolicyByPriority :one
SELECT id, name, priority, budget_minutes, schedule_mode, active, created_at FROM sla_policies
WHERE priority = $1
  AND active
`

// Resolves the policy for a new ticket. The partial unique index on
// (priority) WHERE active guarantees this returns at most one row, so :one is
// a claim the database enforces rather than an assumption.
func (q *Queries) GetActiveSLAPolicyByPriority(ctx context.Context, priority domain.Priority) (SlaPolicy, error) {
	row := q.db.QueryRow(ctx, getActiveSLAPolicyByPriority, priority)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.BudgetMinutes,
		&i.ScheduleMode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getSLAPolicyByID = `-- name: GetSLAPolicyByID :one
SELECT id, name, priority, budget_minutes, schedule_mode, active, created_at FROM sla_policies
WHERE id = $1
`

// The policy a ticket was snapshotted with. Looked up by id rather than by
// priority so that editing a policy does not retroactively move the deadlines
// of tickets created under the old budget.
func (q *Queries) GetSLAPolicyByID(ctx context.Context, id int64) (SlaPolicy, error) {
	row := q.db.QueryRow(ctx, getSLAPolicyByID, id)
	var i SlaPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Priority,
		&i.BudgetMinutes,
		&i.ScheduleMode,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveSLAPolicies = `-- name: ListActiveSLAPolicies :many
SELECT id, name, priority, budget_minutes, schedule_mode, active, created_at FROM sla_policies
WHERE active
ORDER BY budget_minutes
`

// Ordered by budget so the result reads from most to least urgent. Sorting by
// the priority label would be alphabetical, which is meaningless here.
func (q *Queries) ListActiveSLAPolicies(ctx context.Context) ([]SlaPolicy, error) {
	rows, err := q.db.Query(ctx, listActiveSLAPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SlaPolicy
	for rows.Next() {
		var i SlaPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Priority,
			&i.BudgetMinutes,
			&i.ScheduleMode,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
