// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package ticketdb

import (
	"time"

	domain "github.com/JoseDavidGarciaDowning/sla-desk/internal/modules/ticket/domain"
	uuid "github.com/google/uuid"
)

type Ticket struct {
	ID                uuid.UUID
	RequesterID       uuid.UUID
	AssigneeID        *uuid.UUID
	Title             string
	Description       string
	Category          domain.Category
	Priority          domain.Priority
	Status            domain.Status
	SlaPolicyID       int64
	SlaConsumedMicros int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
	SlaBreachedAt     *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type TicketStatusHistory struct {
	ID         int64
	TicketID   uuid.UUID
	FromStatus *domain.Status
	ToStatus   domain.Status
	ActorID    uuid.UUID
	ActorRole  domain.ActorRole
	Reason     *string
	CreatedAt  time.Time
}
