// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package ticketdb

import (
	"context"
	"time"

	domain "github.com/JoseDavidGarciaDowning/sla-desk/internal/modules/ticket/domain"
	uuid "github.com/google/uuid"
)

const assignTicket = `-- name: AssignTicket :one
UPDATE tickets
   SET assignee_id = $1::uuid,
       updated_at  = now()
 WHERE id = $2
RETURNING id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at
`

type AssignTicketParams struct {
	AssigneeID *uuid.UUID
	ID         uuid.UUID
}

// Puts an agent on a ticket, or takes whoever is there off it.
//
// One column. No ticket_status_history row is written by this or alongside it,
// and that is a decision rather than an omission (tasks/slice-2/plan.md §E):
// the history is the fact the SLA clock is rebuilt from (docs/spec.md §4.2),
// and assignment does not move a ticket's status. A row for it would pad the
// timeline sla.Reconstruct walks, and the consistency test would be right to
// fail. Who assigned what to whom belongs to the audit log in slice 9.
//
// Nothing here checks that the assignee may hold tickets. assignee_id is a bare
// foreign key to users, so this statement would accept a customer's id — the
// check is a port the module declares and the composition root answers. A CHECK
// constraint joining users.role was rejected: it would freeze the answer, and
// demoting an agent who still holds open tickets would then fail at write time.
//
// No rows means no such ticket, which the handler turns into a 404.
func (q *Queries) AssignTicket(ctx context.Context, arg AssignTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, assignTicket, arg.AssigneeID, arg.ID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    requester_id,
    title,
    description,
    category,
    priority,
    sla_policy_id,
    status,
    sla_clock_started_at,
    sla_due_at
)
VALUES ($1, $2, $3, $4, $5, $6, 'open', $7, $8)
RETURNING id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at
`

type CreateTicketParams struct {
	RequesterID       uuid.UUID
	Title             string
	Description       string
	Category          domain.Category
	Priority          domain.Priority
	SlaPolicyID       int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
}

// A new ticket is always open, so the clock is always running and the two
// CHECK constraints require both clock columns to be set. They are parameters
// rather than expressions because every deadline in this system is computed by
// internal/sla and nowhere else (docs/spec.md §4.2).
//
// The caller must write the matching ticket_status_history row (NULL -> open)
// in the same transaction. No history row, no transition — §4.1.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.RequesterID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Priority,
		arg.SlaPolicyID,
		arg.SlaClockStartedAt,
		arg.SlaDueAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets WHERE id = $1
`

// One ticket, for a caller who is not its requester.
//
// The counterpart to GetTicketForRequester, and a separate query rather than
// that one with the predicate made conditional — the same decision as the queue
// (tasks/slice-2/plan.md decision B). The scoped one keeps its predicate and
// takes no new parameter, so it cannot be talked into returning someone else's
// ticket by any argument.
//
// Reachable only from a handler mounted behind RequireRole. Nothing here
// enforces that, which is stated rather than hidden.
//
// No rows still means 404 at the boundary. The agent group answers 403 to a
// customer because there is no id in its path to confirm; an id that names no
// ticket is a different question, and §11's rule applies to it unchanged.
func (q *Queries) GetTicketByID(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketForRequester = `-- name: GetTicketForRequester :one
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets
WHERE id = $1
  AND requester_id = $2
`

type GetTicketForRequesterParams struct {
	ID          uuid.UUID
	RequesterID uuid.UUID
}

// The requester predicate lives in the SQL, not in the handler. A forgotten
// check in Go must not be enough to leak another customer's ticket
// (docs/spec.md §4.3). Returning no rows rather than a row the caller must then
// reject is also what lets the API answer 404 instead of 403, which would
// confirm the ticket exists.
func (q *Queries) GetTicketForRequester(ctx context.Context, arg GetTicketForRequesterParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForRequester, arg.ID, arg.RequesterID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketForUpdate = `-- name: GetTicketForUpdate :one
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets
WHERE id = $1
FOR UPDATE
`

// Reads a ticket and holds it for the rest of the transaction.
//
// FOR UPDATE, not a plain read. Two transitions arriving at once — an agent
// resolving while the customer replies — would otherwise both read the same
// current status, both compute a clock from it, and the second commit would
// overwrite the first with a cache that never accounted for it. The lock makes
// them queue.
//
// Not scoped by requester: an agent transitions tickets that are not theirs.
// Authorisation for that lives in the RBAC matrix, not in this query.
func (q *Queries) GetTicketForUpdate(ctx context.Context, id uuid.UUID) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForUpdate, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketPolicyID = `-- name: GetTicketPolicyID :one
SELECT sla_policy_id FROM tickets
WHERE id = $1
`

// The policy a ticket was created under, read without locking anything.
//
// It exists so the SLA clock can be resolved before Transition opens its
// transaction, which is what keeps another module's I/O out of ours. The read
// is safe unlocked because sla_policy_id is written once by CreateTicket and no
// query updates it — and Transition does not take that on trust: it compares
// this against the locked row before writing.
func (q *Queries) GetTicketPolicyID(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTicketPolicyID, id)
	var sla_policy_id int64
	err := row.Scan(&sla_policy_id)
	return sla_policy_id, err
}

const listTicketsByRequester = `-- name: ListTicketsByRequester :many
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets
WHERE requester_id = $1
  AND ($2::text IS NULL OR status = $2::text)
  AND ($3::text IS NULL OR priority = $3::text)
  AND (
    $4::timestamptz IS NULL
    OR (created_at, id) < ($4::timestamptz, $5::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $6
`

type ListTicketsByRequesterParams struct {
	RequesterID    uuid.UUID
	Status         *string
	Priority       *string
	AfterCreatedAt *time.Time
	AfterID        *uuid.UUID
	PageSize       int32
}

// One page of the caller's tickets, newest first.
//
// Keyset pagination, not OFFSET. OFFSET counts rows from the start every time,
// so a ticket created while someone is paging shifts everything down and they
// see a row twice — and the cost grows with the offset. Carrying the last row's
// sort key instead makes each page independent of what happened to the ones
// before it, and the predicate rides the (requester_id, created_at DESC) index.
//
// The key is (created_at, id), not created_at alone: two tickets created in the
// same transaction share a timestamp, and a cursor on a non-unique key can
// either skip rows or repeat them.
//
// status and priority are optional filters, applied here rather than in the
// browser. Filtering a loaded page on the client filters only that page, so
// with pagination it lies: "you have 3 open tickets" because the other seven
// were on page two. One query rather than four, so the cursor means the same
// thing under every combination of filters.
//
// These two parameters come out as *string rather than as *ticket.Status and
// *ticket.Priority, and that is the least bad of three measured options. Every
// other column in this file carries its domain type; these do not, because
// sqlc will give a nullable parameter either the right type or the right
// nullability, not both:
//
//	sqlc.narg(status)::text              -> *string          (this one)
//	status = COALESCE(sqlc.narg(status), status)
//	                                     -> ticket.Status, NOT a pointer.
//	                                        An absent filter is then the zero
//	                                        value, pgx sends '' rather than
//	                                        NULL, COALESCE('', status) is '',
//	                                        and asking for no filter returns
//	                                        no rows. Silently.
//	...COALESCE(NULLIF(narg, ''), col)   -> interface{}. Inference gives up.
//
// A pointer says "absent" and cannot be confused with a value. Losing the
// domain type on two parameters costs one conversion in the handler, which the
// handler has to do anyway: it validates the incoming query string against the
// vocabulary before it gets here.
func (q *Queries) ListTicketsByRequester(ctx context.Context, arg ListTicketsByRequesterParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByRequester,
		arg.RequesterID,
		arg.Status,
		arg.Priority,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.SlaPolicyID,
			&i.SlaConsumedMicros,
			&i.SlaClockStartedAt,
			&i.SlaDueAt,
			&i.SlaBreachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketsForQueue = `-- name: ListTicketsForQueue :many
SELECT t.id, t.requester_id, t.assignee_id, t.title, t.description, t.category, t.priority, t.status, t.sla_policy_id, t.sla_consumed_micros, t.sla_clock_started_at, t.sla_due_at, t.sla_breached_at, t.created_at, t.updated_at, u.name AS requester_name, u.email AS requester_email
FROM tickets t
JOIN users u ON u.id = t.requester_id
WHERE ($1::text IS NULL OR t.status = $1::text)
  AND ($2::text IS NULL OR t.priority = $2::text)
  AND (
    $3::text = 'any'
    OR ($3::text = 'unassigned' AND t.assignee_id IS NULL)
    OR ($3::text = 'one' AND t.assignee_id = $4::uuid)
  )
  AND (
    $5::timestamptz IS NULL
    OR (COALESCE(t.sla_due_at, '9999-12-31 23:59:59.999999+00'::timestamptz), t.id) >
       ($5::timestamptz, $6::uuid)
  )
ORDER BY COALESCE(t.sla_due_at, '9999-12-31 23:59:59.999999+00'::timestamptz), t.id
LIMIT $7
`

type ListTicketsForQueueParams struct {
	Status         *string
	Priority       *string
	AssigneeFilter string
	AssigneeID     *uuid.UUID
	AfterDueAt     *time.Time
	AfterID        *uuid.UUID
	PageSize       int32
}

type ListTicketsForQueueRow struct {
	ID                uuid.UUID
	RequesterID       uuid.UUID
	AssigneeID        *uuid.UUID
	Title             string
	Description       string
	Category          domain.Category
	Priority          domain.Priority
	Status            domain.Status
	SlaPolicyID       int64
	SlaConsumedMicros int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
	SlaBreachedAt     *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
	RequesterName     *string
	RequesterEmail    string
}

// One page of EVERY ticket, in deadline order. The agent queue.
//
// A separate query rather than ListTicketsByRequester with the predicate made
// conditional, and that is the decision slice 2 exists to make
// (tasks/slice-2/plan.md decision B). Passing a role in and skipping
// WHERE requester_id when it says 'agent' would put a boolean in charge of a
// security predicate — and T14a's mutation testing already caught that exact
// shape once, when a query was scoped for the case a test happened to run and
// open for the one it did not. The customer's query keeps its predicate, takes
// no new parameter, and cannot be talked into returning someone else's ticket.
//
// What replaces the predicate is where this query may be called from: only
// handlers mounted under /api/agent, behind RequireRole. Nothing here enforces
// anything, and that is stated rather than hidden.
//
// ORDER BY the deadline, not created_at. A queue is read to find what breaches
// next; ordering by age makes the agent hunt for it, and sorting the loaded
// page in the browser sorts one page of many — the same lie client-side
// filtering told in T14a.
//
// COALESCE(sla_due_at, sentinel) rather than NULLS LAST, because the cursor has
// to compare against the same expression and (NULL, id) > (x, id) is NULL, not
// false. The sentinel is 9999-12-31T23:59:59.999999Z rather than 'infinity'
// because the generated cursor parameter is *time.Time, which cannot hold one.
// See db/migrations/004. The matching expression index is what makes this an
// Index Cond rather than a Filter.
//
// The cursor is (deadline, id) and not (created_at, id): a keyset cursor IS a
// position in the sort order, so it must carry the key being sorted on.
// Carrying a different one asks the database for "what comes after the row
// created at 10:00" in a list ordered by deadline, which means nothing.
//
// Known and accepted: sla_due_at is mutable — pausing a ticket clears it and
// resuming recomputes it — so a ticket transitioned while someone is paging can
// move across the cursor and be seen twice or missed. Only the row that moved
// is affected, which is the one an agent just acted on. OFFSET would shift
// every row after it instead, on any insert as well.
//
// assignee is three questions, not one: any assignee, a specific one, or none.
// @assignee_filter distinguishes them because a NULL parameter already means
// "no filter" and cannot also mean "unassigned".
func (q *Queries) ListTicketsForQueue(ctx context.Context, arg ListTicketsForQueueParams) ([]ListTicketsForQueueRow, error) {
	rows, err := q.db.Query(ctx, listTicketsForQueue,
		arg.Status,
		arg.Priority,
		arg.AssigneeFilter,
		arg.AssigneeID,
		arg.AfterDueAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsForQueueRow
	for rows.Next() {
		var i ListTicketsForQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.SlaPolicyID,
			&i.SlaConsumedMicros,
			&i.SlaClockStartedAt,
			&i.SlaDueAt,
			&i.SlaBreachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RequesterName,
			&i.RequesterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTicketClock = `-- name: UpdateTicketClock :one
UPDATE tickets
SET status               = $1,
    sla_consumed_micros  = $2,
    sla_clock_started_at = $3,
    sla_due_at           = $4,
    updated_at           = $5
WHERE id = $6
RETURNING id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at
`

type UpdateTicketClockParams struct {
	Status            domain.Status
	SlaConsumedMicros int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
	UpdatedAt         time.Time
	ID                uuid.UUID
}

// Writes the derived cache. Step 4 of the order fixed by docs/adr/0001, and it
// runs only after the history row exists and the clock has been rebuilt from
// the history including it.
//
// The two CHECK constraints on tickets mean this cannot store an incoherent
// pair: a status other than open with a running clock, or a clock without a
// deadline, is rejected by the database rather than trusted to the caller.
func (q *Queries) UpdateTicketClock(ctx context.Context, arg UpdateTicketClockParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicketClock,
		arg.Status,
		arg.SlaConsumedMicros,
		arg.SlaClockStartedAt,
		arg.SlaDueAt,
		arg.UpdatedAt,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
