// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package identitydb

import (
	"context"
)

const getUserByClerkID = `-- name: GetUserByClerkID :one
SELECT id, clerk_user_id, email, name, role, created_at, updated_at FROM users
WHERE clerk_user_id = $1
`

func (q *Queries) GetUserByClerkID(ctx context.Context, clerkUserID string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkID, clerkUserID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserFromClerk = `-- name: UpsertUserFromClerk :one
INSERT INTO users (clerk_user_id, email, name, role)
VALUES ($1, $2, $3, 'customer')
ON CONFLICT (clerk_user_id) DO UPDATE
SET email      = EXCLUDED.email,
    name       = EXCLUDED.name,
    updated_at = now()
RETURNING id, clerk_user_id, email, name, role, created_at, updated_at
`

type UpsertUserFromClerkParams struct {
	ClerkUserID string
	Email       string
	Name        *string
}

// The idempotent provisioning path from docs/spec.md §4.5. Both the Clerk
// webhook and the lazy fallback in RequireAuth call this, so whichever request
// arrives first creates the row and the other one is a harmless update. That is
// what removes the signup race entirely.
//
// The role is written as a literal on insert and is deliberately absent from the
// update clause. A webhook payload must never be able to promote a user, and
// re-running this on an existing agent must not demote them back to customer.
func (q *Queries) UpsertUserFromClerk(ctx context.Context, arg UpsertUserFromClerkParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserFromClerk, arg.ClerkUserID, arg.Email, arg.Name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkUserID,
		&i.Email,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
