// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clock.sql

package store

import (
	"context"
	"time"
)

const transactionTime = `-- name: TransactionTime :one
SELECT now()::timestamptz AS transaction_time
`

// The single instant a write transaction is stamped with.
//
// now() is the transaction timestamp, so every call inside one transaction
// returns the same value. Reading it here, rather than taking time.Now() in Go,
// is what keeps deadlines on the database's clock: the breach worker selects
// WHERE sla_due_at < now(), and a deadline derived from an API instance's clock
// would be shifted by whatever that instance's drift happens to be. On Cloud
// Run there is more than one instance and no reason to expect them to agree.
func (q *Queries) TransactionTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, transactionTime)
	var transaction_time time.Time
	err := row.Scan(&transaction_time)
	return transaction_time, err
}
