// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	ticket "github.com/JoseDavidGarciaDowning/sla-desk/internal/ticket"
	"github.com/jackc/pgx/v5/pgtype"
)

type SlaPolicy struct {
	ID            int64
	Name          string
	Priority      ticket.Priority
	BudgetMinutes int32
	ScheduleMode  string
	Active        bool
	CreatedAt     time.Time
}

type Ticket struct {
	ID                pgtype.UUID
	RequesterID       pgtype.UUID
	AssigneeID        pgtype.UUID
	Title             string
	Description       string
	Category          ticket.Category
	Priority          ticket.Priority
	Status            ticket.Status
	SlaPolicyID       int64
	SlaConsumedMicros int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
	SlaBreachedAt     *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type TicketStatusHistory struct {
	ID         int64
	TicketID   pgtype.UUID
	FromStatus *ticket.Status
	ToStatus   ticket.Status
	ActorID    pgtype.UUID
	ActorRole  ticket.Role
	Reason     *string
	CreatedAt  time.Time
}

type User struct {
	ID          pgtype.UUID
	ClerkUserID string
	Email       string
	Name        *string
	Role        ticket.Role
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
