// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	ticket "github.com/JoseDavidGarciaDowning/sla-desk/internal/ticket"
	"github.com/jackc/pgx/v5/pgtype"
)

type SlaPolicy struct {
	ID            int64
	Name          string
	Priority      ticket.Priority
	BudgetMinutes int32
	ScheduleMode  string
	Active        bool
	CreatedAt     time.Time
}

type User struct {
	ID          pgtype.UUID
	ClerkUserID string
	Email       string
	Name        *string
	Role        ticket.Role
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
