// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package store

import (
	"context"
	"time"

	ticket "github.com/JoseDavidGarciaDowning/sla-desk/internal/ticket"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (
    requester_id,
    title,
    description,
    category,
    priority,
    sla_policy_id,
    status,
    sla_clock_started_at,
    sla_due_at
)
VALUES ($1, $2, $3, $4, $5, $6, 'open', $7, $8)
RETURNING id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at
`

type CreateTicketParams struct {
	RequesterID       pgtype.UUID
	Title             string
	Description       string
	Category          ticket.Category
	Priority          ticket.Priority
	SlaPolicyID       int64
	SlaClockStartedAt *time.Time
	SlaDueAt          *time.Time
}

// A new ticket is always open, so the clock is always running and the two
// CHECK constraints require both clock columns to be set. They are parameters
// rather than expressions because every deadline in this system is computed by
// internal/sla and nowhere else (docs/spec.md §4.2).
//
// The caller must write the matching ticket_status_history row (NULL -> open)
// in the same transaction. No history row, no transition — §4.1.
func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.RequesterID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.Priority,
		arg.SlaPolicyID,
		arg.SlaClockStartedAt,
		arg.SlaDueAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTicketForRequester = `-- name: GetTicketForRequester :one
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets
WHERE id = $1
  AND requester_id = $2
`

type GetTicketForRequesterParams struct {
	ID          pgtype.UUID
	RequesterID pgtype.UUID
}

// The requester predicate lives in the SQL, not in the handler. A forgotten
// check in Go must not be enough to leak another customer's ticket
// (docs/spec.md §4.3). Returning no rows rather than a row the caller must then
// reject is also what lets the API answer 404 instead of 403, which would
// confirm the ticket exists.
func (q *Queries) GetTicketForRequester(ctx context.Context, arg GetTicketForRequesterParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketForRequester, arg.ID, arg.RequesterID)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AssigneeID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.Priority,
		&i.Status,
		&i.SlaPolicyID,
		&i.SlaConsumedMicros,
		&i.SlaClockStartedAt,
		&i.SlaDueAt,
		&i.SlaBreachedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTicketsByRequester = `-- name: ListTicketsByRequester :many
SELECT id, requester_id, assignee_id, title, description, category, priority, status, sla_policy_id, sla_consumed_micros, sla_clock_started_at, sla_due_at, sla_breached_at, created_at, updated_at FROM tickets
WHERE requester_id = $1
  AND (
    $2::timestamptz IS NULL
    OR (created_at, id) < ($2::timestamptz, $3::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $4
`

type ListTicketsByRequesterParams struct {
	RequesterID    pgtype.UUID
	AfterCreatedAt *time.Time
	AfterID        pgtype.UUID
	PageSize       int32
}

// One page of the caller's tickets, newest first.
//
// Keyset pagination, not OFFSET. OFFSET counts rows from the start every time,
// so a ticket created while someone is paging shifts everything down and they
// see a row twice — and the cost grows with the offset. Carrying the last row's
// sort key instead makes each page independent of what happened to the ones
// before it, and the predicate rides the (requester_id, created_at DESC) index.
//
// The key is (created_at, id), not created_at alone: two tickets created in the
// same transaction share a timestamp, and a cursor on a non-unique key can
// either skip rows or repeat them.
func (q *Queries) ListTicketsByRequester(ctx context.Context, arg ListTicketsByRequesterParams) ([]Ticket, error) {
	rows, err := q.db.Query(ctx, listTicketsByRequester,
		arg.RequesterID,
		arg.AfterCreatedAt,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ticket
	for rows.Next() {
		var i Ticket
		if err := rows.Scan(
			&i.ID,
			&i.RequesterID,
			&i.AssigneeID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.Status,
			&i.SlaPolicyID,
			&i.SlaConsumedMicros,
			&i.SlaClockStartedAt,
			&i.SlaDueAt,
			&i.SlaBreachedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
