// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ticket_status_history.sql

package store

import (
	"context"

	ticket "github.com/JoseDavidGarciaDowning/sla-desk/internal/ticket"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTicketStatusHistory = `-- name: InsertTicketStatusHistory :one
INSERT INTO ticket_status_history (
    ticket_id,
    from_status,
    to_status,
    actor_id,
    actor_role,
    reason
)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ticket_id, from_status, to_status, actor_id, actor_role, reason, created_at
`

type InsertTicketStatusHistoryParams struct {
	TicketID   pgtype.UUID
	FromStatus *ticket.Status
	ToStatus   ticket.Status
	ActorID    pgtype.UUID
	ActorRole  ticket.Role
	Reason     *string
}

// Written in the same transaction as the ticket update it describes. This table
// is the fact the SLA clock is rebuilt from; the sla_* columns on tickets are a
// cache of it (docs/spec.md §4.2).
//
// from_status is NULL only on the row that records creation.
func (q *Queries) InsertTicketStatusHistory(ctx context.Context, arg InsertTicketStatusHistoryParams) (TicketStatusHistory, error) {
	row := q.db.QueryRow(ctx, insertTicketStatusHistory,
		arg.TicketID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ActorID,
		arg.ActorRole,
		arg.Reason,
	)
	var i TicketStatusHistory
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ActorID,
		&i.ActorRole,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const listTicketStatusHistory = `-- name: ListTicketStatusHistory :many
SELECT id, ticket_id, from_status, to_status, actor_id, actor_role, reason, created_at FROM ticket_status_history
WHERE ticket_id = $1
ORDER BY created_at, id
`

// The input to sla.Reconstruct, and the ticket timeline in the UI.
//
// Ordered by id as well as created_at so that two rows sharing a timestamp
// still come back in a fixed order. Reconstruction walks this sequence, so an
// unstable order would make the clock depend on how Postgres felt about the
// tie.
func (q *Queries) ListTicketStatusHistory(ctx context.Context, ticketID pgtype.UUID) ([]TicketStatusHistory, error) {
	rows, err := q.db.Query(ctx, listTicketStatusHistory, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketStatusHistory
	for rows.Next() {
		var i TicketStatusHistory
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.FromStatus,
			&i.ToStatus,
			&i.ActorID,
			&i.ActorRole,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
